sudo: false
language: java
jdk:
- oraclejdk8
script:
- test/run.sh
notifications:
  slack:
    secure: kqb+xlDDpY/v/gzmN/3P4q12d7StpBYhjNFhKtBrz6dTDK/NxlXDFLcVSjW6gBUomMD8O+5jczFkS/RZLMCvVfq3xg5zr+MYfqM4DiIDh1fUDCYaXhFy2Jn9nZFUZ0uQFEyG/YoRD0TgocST5I1GkixYeW4MuelHfSxpYBbEU+aWRJ0crP8wGUqSqWXShNsVb6UOmIsXUmse72bxHPgQGlDkZKhyWznYT8YOYF00sI71Ef66KCblO3t0k+Xyv1Y50oWMv77GrXWtHKtCKq5qqFvgOAypZWM9LmzXTMX4myCrGhN10o+UfZUDheUJ/GmYh7E0lCcG01eZJ/gsiF8RI2RPklUrLjwhxM4z9M+M1xfh7rrir/Jot0uLskINK2TaK9dEtQW/KEJsNxvRiGla4XR6SfUOz7F/iQ1l/ZRvq7udOJrPlZbByjMutl/Sx3156pQ7zcj/FpiEnCjF5t9uMe6oCaHcMpvkMi0ITY1pBPyvOXkzinVLv7V5HirYhcwgZHHP1Ulatfz6wj3MTIHOkxc+fJ5/Pc4i70UoAhkWKliStyzne5TyU7QVxzE5daO+DRRsMByBKQRcVGcd2qC1N+eV4pyAr95ngjM0eGnZxiZXWhlD0vO2zJAC3W35NXDH7uE+nMprZaF2UgFjMzAvu+HQtQR9GZHmyjeVTMMNFJo=
